### ISSUE TITLE
Flashing M for "million" in resistance mode

### ISSUE THREAD

**Issue by Ownasaurus** [inflex/BK-390A#1]
As noted on Louis Rossmann's stream, the "M" before the "ohm" character flashes on and off in the cases of high resistance.

I do not know if this is when using the command line version or the win32 version.

It is currently unknown if a similar problem exists for other unit prefixes as I do not own the hardware to test and debug.

**Comment by ghost** [comment]
It's in the Windows GUI version (GDI).
I was going to get Louis to drop me a data dump from his meter, as I'm wondering if I've missed something.   It's annoying to me too and so I would like to get it fixed up.  Having the meter data from Louis would be the most useful thing to me right now, as I too do not have a BK390A meter, so the whole thing has been done just from the spec sheet.

**Comment by Ownasaurus** [comment]
Very interesting. I would be interested to see the data dump too if you are willing to share. Thanks for your work on this project.

If I have time this weekend, I may write some code to enumerate the available serial ports and try sending and receiving a command/response pair to auto-defect the port the BK390A is on.

**Comment by ghost** [comment]
That'd be good if you can add that; saves another parameter having to be explicitly set.

At least this meter does have a fixed set of comms parameters (rate/bits/stop),  I just left it generic for any future adaptations to other meters that people might try.

I'm not sure if there was any data-send options to the meter (just listen only), but you should see the same frame-start sequences within a second or two, so that could be your way of testing.

**Comment by Ownasaurus** [comment]
Thanks for the info. Just downloaded the serial protocol manual, and hopefully I can look at it later this week.

**Comment by Ownasaurus** [comment]
Reviewed the code and the documentation. Code looks pretty sane regarding the "prefix". Would be curious to know if it occurs in any of the other modes (current, etc.)

**Comment by Ownasaurus** [comment]
Can confirm it happens in other modes.  For example, at around https://youtu.be/3YGCFeZZS6A?t=20m38s (watch about 20 seconds), it happens with V and mV.

**Comment by Ownasaurus** [comment]
Another observation is that the multimeter data is updating only about once a second, but the units glitch happens within a single digit update. Ex: V changes to mV then changes back to V every time the digits get updated. I think it therefore must be somehow clearing the prefix while the code is waiting for more serial data.
With that said, I can't figure out where this could possibly occur in the code....

**Comment by Ownasaurus** [comment]
I was wondering if you are able to get in touch with Louis and if he is willing to run the software in debug mode to help us diagnose this problem. Maybe we can even add some extra debug prints to help with this.

**Comment by ghost** [comment]
I've asked him several times.  It's just a waiting game.  Most of my debugging in the past is purely from what's seen on the videos, that's about all the debugging data you get, which leads to false fixes occasionally.    What'd be best is to have access to one of these meters.

**Comment by Ownasaurus** [comment]
Gotcha. I've looked at the code so many times and just cannot figure out what's causing this one character to disappear!
If time is an issue and he's willing to trust me, I wonder if he'd be willing to ship me a meter for testing and debugging (I live one county north of his store in NY) that I can gladly ship back to him when the debugging is complete. I don't know if he has more than one, though, or if he would be willing to trust a "stranger."

**Comment by ghost** [comment]
He's only got the one. What's more realistically going to happen is someone who owns the meter might finally stumble on to this and participate.

**Comment by Ownasaurus** [comment]
Let's hope so! Or I thought about writing a serial port emulator that sends data in that format... but probably not worth the time. Let's just hope for a user willing to do a -d !

**Comment by Ownasaurus** [comment]
One more thing -- I also noticed that it doesn't seem to keep a a space either. That is, the prefix appears to be emptystring, even though you set it to a space or a character every time. That is why the width keeps changing.

Is it possible in the end, an older version is being used? Just want to rule that out.  Thanks!

**Comment by ghost** [comment]
I fixed that on my local version here, keeps a fixed width.

**Comment by Ownasaurus** [comment]
I guess that makes me wonder how old of a version he is using. Is it possible the flashing prefix is fixed in the current version as well?

**Comment by codemachine** [comment]
There appears to be a lot of missing default cases in various switch statements in the code which could be part of the problem. Ideally these would be logged.

I also noticed in the datasheet it says "The serial data is sent to SDO pin twice every A/D conversion cycle.", it's unclear to me exactly what this means (and my serial-data-fu is lacking), but I wonder if it comes quickly and the second send might have a corrupted range. Perhaps the previous software Louis used was working around this.

And how did you develop this without the multimeter and without an emulator?

**Comment by ghost** [comment]
Developed from the spec, nothing more.  Blind development as it were.

As for the SDO (serial-data-output) thing, it just means that the data is sent twice per A/D conversion and that the buffer simply ( should? ) remain constant, but it would seen there's an ambiguity/nuance being missed which is why at this point getting actual live debugging data would be more useful than more speculation.

As for the missing defaults on the case statements, other than perhaps logging the situation "bit wasn't handled by existing case statement", it's not likely to assist with the situation.  

We just need a debugging run of data, else it's just more blind wandering through the forest. . . . unless someone wants to fork out $ to buy one of the meters ( sorry folks, I've already dumped enough $ in to free projects for now ).

**Comment by codemachine** [comment]
I'm aware of that live debugging data is ideal, I was just trying to suggest alternatives given that it doesn't seem to be forthcoming.

As to the missing defaults, it actually seems to me a corrupted RANGE of something like 0x0F causing falling through seems to be the most likely explanation.

I've also just noticed that ````dps```` is not cleared every loop unlike the other variables, if it was I suspect you'd see that reset too.

**Comment by ghost** [comment]
You get to the point where you choose;  if the data is corrupted, do you act on it, or ignore it.  
The latter is being opted currently, particularly given that we're uncertain as to the nature of the data.

I'll ask Louis a few more times for data, but beyond that someone really just needs to get their own meter, or find someone who has it ( who originally influenced Louis to buy this one? ).  

It's hard enough getting him to get the time to update important things, let alone smaller (but annoying) things like this.  At this stage, I'd say someone has to buy/borrow one (not from Louis) and when it's proven to work properly that's when we can finally push it to Louis and say "Here, it's working 100%".

**Comment by codemachine** [comment]
Yes, I realise that's not totally conclusive and I understand the reticence to play around without the data.

I did just find something else though that you may not have been aware of, I previously only saw the document on the B&K site, but I found the full manual for some boards, and it appears that one or both of these are the same:

http://www.cyrustek.com.tw/spec/ES51962.pdf
http://www.cyrustek.com.tw/spec/ES51978.pdf

It looks like there is at least one other multimeter that uses this, the Peaktech 3315. Perhaps there's more. It might be possible to find some reference code or other multimeters for these.

**Comment by ghost** [comment]
Software looks real familiar... price is steep still ( considering the purpose,  I've got no problem spending $ on a good meter that I'd use though ).

https://www.ebay.com/itm/PeakTech-3315-Digital-USB-Multimeter-Messgerat-Meter-Messer-Digitalmultimeter-/221583963478

**Comment by codemachine** [comment]
This suggests that a lot of multimeters can be hacked to do this:
http://www.flashingleds.net/rs232/rs232.html

**Comment by codemachine** [comment]
It's unclear if the 51962 and 51978 are exactly the same, and which exactly the B&K uses if not, but I did find some other models for both and there are other Cyrustech 519 chips besides these.

Given this and the above you might be able to find something really cheap for this, you might already own something if you're willing to do the hack above.

**Comment by codemachine** [comment]
Actually it looks like the B&K doc is taken from the Cyrustech 51962 manual given the superfluous section at the top of the B&K doc. Peaktech has the same superfluous section.

If true apparently Uni-T UT70B is compatible too.

**Comment by Ownasaurus** [comment]
Interesting different to note though is that the BK390A suggests NO parity for regular serial and ODD parity for serial over usb.
The site codemachine linked to shows a screenshot with EVEN parity.

I wonder why these all differ? Could that be affecting the communication somehow?

**Comment by Ownasaurus** [comment]
Very cool find though that we could probably work with different hardware to get this working :)

**Comment by matthewtuck** [comment]
I can't find anything about even parity (which site?), but the ES519xx chips do seem to have differing protocols.

A parity issue seems like it'd drop all data though.

**Comment by Ownasaurus** [comment]
The screenshot: http://www.flashingleds.net/rs232/dmm-serial-packet.jpg
on the site you linked to: http://www.flashingleds.net/rs232/rs232.html 
suggests an even parity bit

**Comment by codemachine** [comment]
The BK390A docs clearly say odd-parity, so it shouldn't be an issue. Maybe a mistake in the screenshot or relevant to another chip.

**Comment by ghost** [comment]
I think within a second we can see what's going on with the flickering looking at this data.

```
Run 1 with 1.4k resistor
  Meter displays:
     RS232 AUTO
     1.473 k(omega symbol)

C:\Users\mark\Downloads\bk390_app>win-bk390a.exe -d -z 120 -p 3 -s 2400:7o1 -m -fc #10ff10 -bc #000000 -wx 480 -wy 60 -fw 600
Port COM3 Opened
        Baudrate = 2400
        ByteSize = 7
        StopBits = 0
        Parity   = 1
        Setting time-outs successful
        CommMask successful
DATA START: 31 31 34 37 33 33 30 30 32 0d 0a :END
DATA START: 31 31 34 37 33 33 30 30 32 0d 0a :END
DATA START: 0a :END
DATA START: 31 31 34 37 33 33 30 30 32 0d 0a :END
DATA START: 31 31 34 37 33 33 30 30 32 0d 0a :END
DATA START: 0a :END
DATA START: 31 31 34 37 33 33 30 30 32 0d 0a :END
DATA START: 31 31 34 37 33 33 30 30 32 0d 0a :END
DATA START: 0a :END
DATA START: 31 31 34 37 33 33 30 30 32 0d 0a :END
DATA START: 31 31 34 37 33 33 30 30 32 0d 0a :END
DATA START: 0a :END
DATA START: 31 31 34 37 33 33 30 30 32 0d 0a :END
DATA START: 31 31 34 37 33 33 30 30 32 0d 0a :END
DATA START: 0a :END


Run 2 with 1k resistor
  Meter displays:
     RS232 AUTO
     98.8 (omega symbol)

C:\Users\mark\Downloads\bk390_app>win-bk390a.exe -d -z 120 -p 3 -s 2400:7o1 -m -fc #10ff10 -bc #000000 -wx 480 -wy 60 -fw 600
Port COM3 Opened
        Baudrate = 2400
        ByteSize = 7
        StopBits = 0
        Parity   = 1
        Setting time-outs successful
        CommMask successful
DATA START: 30 30 39 38 38 33 30 30 32 0d 0a :END
DATA START: 30 30 39 38 38 33 30 30 32 0d 0a :END
DATA START: 0a :END
DATA START: 30 30 39 38 38 33 30 30 32 0d 0a :END
DATA START: 30 30 39 38 38 33 30 30 32 0d 0a :END
DATA START: 0a :END
DATA START: 30 30 39 38 38 33 30 30 32 0d 0a :END
DATA START: 30 30 39 38 38 33 30 30 32 0d 0a :END
DATA START: 0a :END
DATA START: 30 30 39 38 38 33 30 30 32 0d 0a :END
DATA START: 30 30 39 38 38 33 30 30 32 0d 0a :END
DATA START: 0a :END
DATA START: 30 30 39 38 38 33 30 30 32 0d 0a :END
DATA START: 30 30 39 38 38 33 30 30 32 0d 0a :END
DATA START: 0a :END


Run 3 with shorted leads
  Meter displays:
     RS232 AUTO
     0.6 (omega symbol)

C:\Users\mark\Downloads\bk390_app>win-bk390a.exe -d -z 120 -p 3 -s 2400:7o1 -m -fc #10ff10 -bc #000000 -wx 480 -wy 60 -fw 600
Port COM3 Opened
        Baudrate = 2400
        ByteSize = 7
        StopBits = 0
        Parity   = 1
        Setting time-outs successful
        CommMask successful
DATA START: 30 30 30 30 36 33 30 30 32 0d 0a :END
DATA START: 30 30 30 30 36 33 30 30 32 0d 0a :END
DATA START: 0a :END
DATA START: 30 30 30 30 36 33 30 30 32 0d 0a :END
DATA START: 30 30 30 30 36 33 30 30 32 0d 0a :END
DATA START: 0a :END
DATA START: 30 30 30 30 36 33 30 30 32 0d 0a :END
DATA START: 30 30 30 30 36 33 30 30 32 0d 0a :END
DATA START: 0a :END
DATA START: 30 30 30 30 35 33 30 30 32 0d 0a :END
DATA START: 30 30 30 30 35 33 30 30 32 0d 0a :END
DATA START: 0a :END
DATA START: 30 30 30 30 35 33 30 30 32 0d 0a :END
DATA START: 30 30 30 30 35 33 30 30 32 0d 0a :END
DATA START: 0a :END

```

**Comment by Ownasaurus** [comment]
In this case I think a simple length check will do the job. I already had one for my auto port detection code, so I just added the check for every serial 'packet' received too. I think my code changes should be just about ready for review, testing, and merge :)

**Comment by inflex** [comment]
I've ended up storing a copy of the last good frame, and if the next frame is a dud, it replays the previous one.

Code seems to be working now with the tester.

The frame length was being tested already, but there was actually a 1-off error in that, so it amuses me that the code ever worked in the first place.

**Comment by codemachine** [comment]
Right, so the reason the symptom affected the range only is it's the first character in the frame and it's getting hit with 0x0A which will drop into the silent default case - the rest of the frame will remain the same from the previous iteration, not being overwritten.

**Comment by codemachine** [comment]
Just a small robustness issue you may or may not want to deal with, which likely wouldn't occur in practice - it looks like there is no functioning overlength check because the loop will end after the max size without having read the LF and nowhere in the code does it check the ````end_of_frame_received```` variable, it only writes to it.

In practice this would treat the first part as a valid frame and then treat the extra as an invalid underlength frame, but you might want to drop the whole overlength frame.

**Comment by inflex** [comment]
Just sorting out the scaling / display quirks right now, thankfully this person is really quick on the ball for the testing cycle.

After that you'll have to resubmit your PR likely to suit the new changes; then we can finally move forward with the automated stuff.

**Comment by Ownasaurus** [comment]
I fixed the off-by-one in my latest commit in my fork so that the length checks work.
Glad you found a tester. Who is it?
Let me know if I have to resubmit the PR in the end. I've made a lot of good changes (at least in my opinion) hopefully I don't have to rebase to your fork and do them over again.

**Comment by ghost** [comment]
Chap called Mark Stanley.

I've notified the important-person about the new binary, guess we'll see on the next live stream or so if the update has been made.

**Comment by Ownasaurus** [comment]
Cheers to Mark!
Could you put me in touch with him to test the auto port detection code? Then we can be more comfortable merging all changes?

**Comment by ghost** [comment]
I'll send him a message and let him know, and he'll perhaps drop in here and talk on this thread if all goes well.

**Comment by Nullkraft** [comment]
Hello everyone, I was just about to tear down my setup when I got Paul's email inviting me over here.  I would be glad to help.

**Comment by Ownasaurus** [comment]
Fantastic, Nullkraft. Could you please test my fork to see if it works **with** and **without** specifying the port with -p on the commandline?  Thanks!

**Comment by Nullkraft** [comment]
OK, give me a minute to reboot into windows.

**Comment by Nullkraft** [comment]
OK, I see that you've already incorporated Paul's changes.  I tested for the flashing 'm'.  Anyway, I ran it without any command line parameters and it of course took 2 seconds to find the port but it did find it.  Next I ran it with -d and finally I ran it with -p 3 -d and everything seems to be working as advertised.

I noticed a faster startup when specifying the port number.  You might want to add an artificial delay so the end user doesn't think something is wrong with auto detection.  Just saying. ;)

**Comment by ghost** [comment]
Maybe make it write up "Checking port... ", ah but all the comms detection happens before the GDI starts, though you could swap that around.

Just noticed there's a small issue when you've moved the i++ line around, it'll sort of break the debug code afterwards.  I'll let you settle out your changes and then I'll clean that back up.

**Comment by Nullkraft** [comment]
Alright, off to a family event.  I'll check back in later this evening (East coast USA).

**Comment by Ownasaurus** [comment]
@inflex Didn't I fix the debug code? Wasn't the debug message off-by-one before in the error state?
I'll keep working on it as time allows.
Let's move the discussion of my code's errors to my fork's issues section if that is OK, @Nullkraft, to keep this part clean and relevant.

**Comment by Ownasaurus** [comment]
(Or of course we could talk in the merge request thread if we want to keep the discussion in inflex's repo)

**Comment by inflex** [comment]
@Ownasaurus can you check out lines 511~538 for me in the latest update after the PR; wasn't quite sure what you were trying to do in there, I reshuffled some items but if you could explicitly-brace sections or clarify, that'd be great.

Stylistically I prefer variable modifications outside of the if() tests, esp things like if (foo-->x)   or if (--foo > x) type things, just saves some ambiguities ( even though it should be clear to coders, it's more about avoiding future side effects/accidents ).

With code blocks,  the style being used is the opening brace on the same line;

```
if (foo) { 
   ...
} 
```
rather than 
```
if (foo)
{
   ...
}
````
again, a style thing, the rest of the code is (should be ;) ) styled that way afaik.

Other than that, since I don't have a meter here, not much more that I can pick out.

**Comment by Ownasaurus** [comment]
@inflex After carefully reviewing the code, it looks like you got it right. I'd just clean up the comments and it should work as I intended.
What might need tweaking is the number of attempts and the sleep time though. Is sleeping for 1 second sufficient? Is two attempts necessary? (I added that bit in case the meter sent a bad packet followed by the correct data)

**Comment by Ownasaurus** [comment]
nope i'm delusional. fixing again now.

**Comment by ghost** [comment]
Looks like he's updated and it appears to be working - 

https://www.youtube.com/watch?v=TsfaQQc2RAg

**Comment by Ownasaurus** [comment]
Great. My feature will be ready to merged in soon once functionality is confirmed. I'll update the latest PR when it's set.

**Comment by ghost** [comment]
I'm guessing you'll collaborate with Nullkraft for that testing?

**Comment by Ownasaurus** [comment]
Yes it's being done on my fork :)

**Comment by Ownasaurus** [comment]
@pvtinflex one more thing though -- do you have a timestamp showing the units prefix not flashing? i couldnt find it quickly in the hour long video.

**Comment by ghost** [comment]
About 3:50 it starts.

**Comment by Ownasaurus** [comment]
I don't see any measurements that would require a prefix though. I see all voltages being measured that are < 10. But if @Nullkraft says it's working, I believe him anyhow.

**Comment by ghost** [comment]
Usually what would happen is that because of the auto-ranging, it would most times go through the mV range to get to the required one, and that would load up the prefix.  There's also more a few minutes later and it seems to be steady/fine there too.  Typically the blinking 'm' kicks in very quickly.

**Comment by Ownasaurus** [comment]
Oh gotcha. Awesome work!

**Comment by Ownasaurus** [comment]
Me: "greetings. Hoping the new version of the bk-390a software is working out for you (if you're using it)"
Louis: "I never updated"

**Comment by Nullkraft** [comment]
I just came from watching a couple more of his videos and it is clear to me that he set the meter to a fixed range.  When the voltage drops below about 0.470 V it would normally autorange into the milliVolt region.  But it never switches even when you see a number like 0.158 V.   Fixed Range....

**Comment by Nullkraft** [comment]
Note line 13 says COM99...

C:\Users\mark\Downloads\bk390_app>pl-bk390a.exe -d
Port detected: COM3
Port COM3 Opened
        Baudrate = 2400
        ByteSize = 7
        StopBits = 0
        Parity   = 1
        Setting time-outs successful
        CommMask successful
Waiting for 2s to get a data sample
DATA START: 30 30 37 36 37 3b 34 30 38 0d 0a :END
LENGTH CHECK: SUCCESS
DATA FORMAT CHECK: SUCCESS
COM99 automatically detected.
DATA START: 30 30 37 36 37 3b 34 30 38 0d 0a :END [11 bytes]
DATA START: 30 30 37 36 37 3b 34 30 38 0d 0a :END [11 bytes]
DATA START: 30 30 37 36 37 3b 34 30 38 0d 0a :END [11 bytes]
DATA START: 30 30 37 36 37 3b 34 30 38 0d 0a :END [11 bytes]
DATA START: 30 30 37 36 37 3b 34 30 38 0d 0a :END [11 bytes]
DATA START: :END [0 bytes]
Invalid number of bytes, expected 11, received 0, loading previous frame
DATA START: 30 30 37 36 37 3b 34 30 38 0d 0a :END [11 bytes]
DATA START: 30 30 37 36 37 3b 34 30 38 0d 0a :END [11 bytes]
DATA START: :END [0 bytes]
Invalid number of bytes, expected 11, received 0, loading previous frame

**Comment by Ownasaurus** [comment]
Right this is @inflex's current version right? That should be one of the things that is fixed in my latest version.
So we still get some funny packets. But that's OK for now since we handle them gracefully. I think my version also has a few of these 0 byte packets.

**Comment by Nullkraft** [comment]
I tried the command line:  win-bk390a.exe -z 120 -p 3 -m -fc #ff1010 -bc #000000 -fw 600
and everything seems to be working fine.  I changed -z a few times and had good control.  I got a rather large red font in the display.

I will mention one thing, when I set -z to a relatively small value (less than 25) the display began to cutoff portions of the information, namely the description(?) such as the word 'Frequency'.

**Comment by ghost** [comment]
@Nullkraft can you do a test with the latest binary I have uploaded here, to see if it produces the "version/build" code in the bottom left corner,  I'm anticipating it to show up something like "B75          Volts" or similar on the bottom

**Comment by Nullkraft** [comment]
I'm seeing [B54] (with the brackets) in the bottom left corner.

By the way, the port detection seems to be working a LOT faster.  Did you do something?

**Comment by Ownasaurus** [comment]
That looks great. And if you ran it with -m you'd probably see it like "[B54] Resistance" or whichever mode its in.
To my knowledge neither of us modified the port detection code any further.

**Comment by Nullkraft** [comment]
That's got it, -m did just as you said.   And you're right, if I hammer the port too quickly I will get the com port error just like before.  Still, it seems to be operating extremely well and is a real pleasure to use at this point.

**Comment by ghost** [comment]
@Nullkraft screenshot? (Demanding, I know :) )

**Comment by Ownasaurus** [comment]
Our do it yourself with my new PR code :D <3

**Comment by Nullkraft** [comment]
Do you need the screenshot for something?  I can jump back to windows if you do.

**Comment by Ownasaurus** [comment]
Prob a screenshot of the GUI with you using -m

**Comment by Nullkraft** [comment]
Here's two with volts and frequency, or would you like to see something else?

Or for some reason I can't drop files in here.  Try:

https://drive.google.com/open?id=1S_7spABVIJSQ1zgiJgRwDWcgYcmnr1rp
      app-z120-m_freq.png and app-z120-m_volts.png

**Comment by ghost** [comment]
Right, that's definitely not what I was hoping for with the [build-version] mod.    I'll think of a better place to put it.

**Comment by Nullkraft** [comment]
There's no 'Help-->About' window?

**Comment by Ownasaurus** [comment]
@pvtinflex how about appending it to the window title? Or did you want to be able to see when someone was streaming with it?

**Comment by ghost** [comment]
Wanted it in-stream.  That's fine, I'll just reposition it perhaps to the bottom-right or such. I need to get other things done today before I play with such trivial things though, must prioritise!

**Comment by Nullkraft** [comment]
OK then.  If you want to work on it this weekend it will have to be Saturday.  I've got another family fun event planned for Sunday.

**Comment by Ownasaurus** [comment]
The good news is I can now compile and test no problem. I got your versioning system to work in Windows build environments. So I can build with #define USE_SERIAL 0 and test GUI whenever since Win is my default OS.

(Can we move conversation to another thread now that the flashing units issue is resolved? :) )
