### ISSUE TITLE
-fpermissive shouldn't be needed anymore, I think

### ISSUE THREAD

**Issue by Ownasaurus** [inflex/BK-390A#6]
https://github.com/inflex/BK-390A/blob/821584fdde4c0d328613ff5a70a644a2bdeec2c9/Makefile#L12

In my makefile, I removed -fpermissive and it compiles with 0 errors and 0 warnings. I added the type casts to suppress the warnings. Do you still get warnings compiling from 'nix without -fpermissive?

**Comment by Ownasaurus** [comment]
Sample output of compilation:
> D:\BK-390A>mingw32-make -f Makefile.win win-bk390a
> g++ -O -static-libgcc -municode -static-libstdc++  win-bk390a.cpp  -o win-bk390a.exe  -lgdi32 -lcomdlg32 -lcomctl32 -lmingw32 -lwinspool
> 
> D:\BK-390A>

**Comment by Ownasaurus** [comment]
Do you have time to try removing -fpermissive from your regular Makefile and try compiling to confirm it is no longer necessary? I can't test and confirm without creating a new Linux environment. Then we will have 0 issues remaining! 🍦 Hooray for stability. If not I understand this is a super minor issue.

**Comment by inflex** [comment]
I see there was a bit of a SNAFU this morning on the Rossmann livestream, welcome to why I don't change things much.

**Comment by Ownasaurus** [comment]
Yes, But he had already been using the updated software successfully for a few hours first I think. Then he fixed it himself after about 3 minutes. I have a feeling it was not a software issue. Though of course I could be completely off.

**Comment by inflex** [comment]
ja, I see he didn't specify what went wrong.  I'm guessing it was a case of he didn't swap it with the old one directly, or he just started running it from a new location, and so didn't have any parameters set up.  Oddly, it's showing v065, could have sworn I loaded v066, no matter.

**Comment by Ownasaurus** [comment]
Can confirm the latest binary you hosted reads v065 in the GUI when ran.

**Comment by ghost** [comment]
At least it's all running now... time to seal it up and waaaaaalk away :D

**Comment by Ownasaurus** [comment]
Yeah it's probably good to leave for a while. I know you'd rather develop your board view software anyway! Buuuut will you resolve the issue in this thread first for completion's sake? (try compiling in 'nix without -fpermissive)  Will help my OCD to see the last issue resolved ;)

**Comment by ghost** [comment]
All done.  

Now to find a new project.

**Comment by Ownasaurus** [comment]
Thanks. Nice working with you. Hopefully I was more helpful than an annoyance! I'll follow this project in case any new features are needed.
